name: MapMorph
version: '1.2'
main: net.mythofy.mapMorph.MapMorph
api-version: '1.20'
authors: [ Kingdragoncat ]
description: Bukkit plugin for map morphing with FAWE, WorldEdit, and WorldGuard
depend: [WorldEdit, WorldGuard, FastAsyncWorldEdit]
softdepend: [PlaceholderAPI]
commands:
  mapmorph:
    description: Main command for MapMorph plugin.
    usage: /<command>
    permission: mapmorph.use
permissions:
  mapmorph.use:
    description: Allows use of MapMorph commands.
    default: op
